# This is the merge resolution showing the conflict, suggestions provided by git, pulling the data from the remote repo, then adding my changes and pushing back to the remote repo

git push -u origin main
To https://github.com/rodu4835/CSPB_3308_Lab04.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/rodu4835/CSPB_3308_Lab04.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.






git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), 350 bytes | 25.00 KiB/s, done.
From https://github.com/rodu4835/CSPB_3308_Lab04
   d76c555..ce793f2  main       -> origin/main
Auto-merging README.md
Merge made by the 'recursive' strategy.
 README.md | 2 ++
 1 file changed, 2 insertions(+)






git status
On branch main
Your branch is ahead of 'origin/main' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean







git push -u origin main
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 16 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 712 bytes | 712.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 2 local objects.
To https://github.com/rodu4835/CSPB_3308_Lab04.git
   ce793f2..9052cd7  main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.
